on:
  pull_request:
    branches:
      - master
    types:
      - closed
    paths:
      - 'CHANGELOG.md'
    condition: |
      startsWith(github.head_ref, 'release-please') &&
      contains(github.event.pull_request.title, 'chore(master)')

name: Push Image to DockerHub
jobs:
  push-to-dockerhub:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: flexer89/beerify-api:latest
    