name: Generate Release Notes

on:
  push:
    branches:
      - master

jobs:
  generate_release_notes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ghrelease-cli

      - name: Generate Release Notes
        run: |
          ghrelease -o owner -r repo -t "${{ secrets.GITHUB_TOKEN }}" generate --pr-labels "enhancement, fix"
