name: Release Workflow

on:
  pull_request:
    branches:
      - master
    types:
      - closed
    condition: |
      startsWith(github.head_ref, 'dev')

permissions:
  contents: write
  pull-requests: write


jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.TOKEN }}
          release-type: node
          package-name: release-please-action
